obj-$(CONFIG_CONSOLE)	+= console_utils_uart.o
obj-$(CONFIG_CONSOLE)	+= console_utils.o
obj-$(CONFIG_CONSOLE)	+= agraph.o

obj-$(CONFIG_I2C)		+= i2c_utils.o

obj-y					+= ascii_utils.o
obj-n					+= ramdiskutils.o

obj-$(CONFIG_TIMER)		+= time_utils.o
obj-$(CONFIG_TIMER)		+= dmtimer_utils.o


obj-$(CONFIG_DISPLAY)		+= display_utils.o
obj-$(CONFIG_DISPLAY)		+= display_utils_dss.o
obj-$(CONFIG_DISPLAY)		+= display_utils_lcdc.o
