obj-$(CONFIG_UART)	+= uart/
obj-$(CONFIG_GPIO)	+= gpio/
obj-$(CONFIG_I2C)	+= i2c/
obj-$(CONFIG_SPI)	+= spi/ 
obj-$(CONFIG_WDT)	+= wdt/
obj-$(CONFIG_SBL_MMCSD)	+= mmc/
obj-$(CONFIG_SBL_MMCSD)	+= ff9b/
obj-$(CONFIG_PMIC) += pmic/
